# Generated by Django 4.2 on 2024-09-24 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_alter_workspace_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
